- bundles/com.zeligsoft.domain.omg.ccm.descriptorgenerator/src/com/zeligsoft/domain/omg/ccm/descriptorgenerator/utils/CDPXtendUtils.java
- bundles/com.zeligsoft.domain.omg.ccm.descriptorgenerator/src/com/zeligsoft/domain/omg/ccm/descriptorgenerator/utils/DescriptorBeautifier.java
Fixing issue#9 by escaping some invalid xml characters which have not been properly escaped before.
> Correctly escape XML characters found in property values

- bundles/com.zeligsoft.domain.idl3plus/src/com/zeligsoft/domain/idl3plus/merge/ClassModelMerger.java
Fixing issue#11 by following the patch provided in github with a small modification: calling the "caseElement" method at the beginning of the "casePackage" method.
> Preserve user added comments when rebuilding an instantiated connector package.

- bundles/com.zeligsoft.domain.dds4ccm/plugin.xml
- bundles/com.zeligsoft.domain.dds4ccm/src/com/zeligsoft/domain/dds4ccm/utils/DDS4CCMMonolithicImplWFRepairer.java
Fix for the issue: "WorkerFunctions need new UUIDs when MonolithicImpl is copied". Applied and tested the patch provided in github.
> Ensure 'worker functions' receive new unique identifiers when containing component is copied.

- bundles/com.zeligsoft.domain.dds4ccm.codegen/src/com/zeligsoft/domain/dds4ccm/codegen/utils/CodeGenUtil.java
From the supplied URI object in the "validateModel" method, get the
existing model resource from the UMLModeler editingDomain, instead of
creating a new resource. This change is required for the selector object
of the IBM ClientContext "com.ibm.xtools.modeler.validation.client" to
recognize the corresponding eObject resource and include the standard
constraints from this ClientContext while validating the eObject.
Also, set the option for including live constraints to 'true'. This
ensures that the constraints with evaluation mode 'live' are included in
addition to 'batch' constraints while applying the batch validation.
Closes #23
> Fix CX utilities/CodeGenUtil model validation bugs

- bundles/com.zeligsoft.domain.dds4ccm.ui.axcioma/.classpath
- bundles/com.zeligsoft.domain.dds4ccm.ui.axcioma/.project
- bundles/com.zeligsoft.domain.dds4ccm.ui.axcioma/.settings/org.eclipse.jdt.core.prefs
- bundles/com.zeligsoft.domain.dds4ccm.ui.axcioma/META-INF/MANIFEST.MF
- bundles/com.zeligsoft.domain.dds4ccm.ui.axcioma/OSGI-INF/l10n/bundle.properties
- bundles/com.zeligsoft.domain.dds4ccm.ui.axcioma/build.properties
- bundles/com.zeligsoft.domain.dds4ccm.ui.axcioma/fragment.xml
- bundles/com.zeligsoft.domain.dds4ccm.ui.axcioma/src/com/zeligsoft/domain/dds4ccm/ui/axcioma/AxciomaSupport.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/plugin.properties
- bundles/com.zeligsoft.domain.dds4ccm.ui/plugin.xml
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/utils/DDS4CCMUIUtil.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/wizards/DDS4CCMModelWizardPage.java
The pop-up menu contribution for refactoring to Axcioma is extracted
from the "com.zeligsoft.domain.dds4ccm.ui" plug-in. It is now
contributed by a newly added fragment which the plug-in is hosting.
Also, for the creation of a new dds4ccm model, the radio button group
for choosing from 'Atcd' and 'Axcioma' in the model wizard is only been
created for a build that includes the above-mentioned fragment.
These changes are required for fixing issue #25: Creating two different installables from a single CX4CBDDS baseline.
> Control Axcioma UI contribution through a plug-in fragment

- bundles/com.zeligsoft.domain.dds4ccm.codegen/src/com/zeligsoft/domain/dds4ccm/codegen/utils/CodeGenUtil.java
For considering a closed resource in workspace, the second parameter of
the 'UMLModeler.getEditingDomain().getResourceSet().getResource(URI uri,
boolean loadOnDemand)' needs to be true. This method is called twice to
keep track of the 'closed/opened' status of the resource before doing
the validation. This allows us to avoid making any changes in the status
of the resource because of applying the validation. Also, precautions
have been taken to avoid any nonexistent uri passed in the validateModel
method.
> Update CodeGenUtil to enforce validation in closed models in workspace

- releng/com.zeligsoft.dds4ccm.update.atcd/rpm_build/zeligsoftCX_atcd.spec
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
RPM scriptlet %pre has been added to do some cleaning up before
proceeding to the installation of the features of a rpm package in the
%post scriptlet. Also, uninstallation of the features of a package is
done only if the package is really being uninstalled, not being
upgraded. The generated rpms from the travis build need to be tested
properly to see if this works.
> Add support to upgrade existing axcioma and atcd installation (Testing).

- bundles/com.zeligsoft.domain.dds4ccm/models/DDS4CCM.emx
- bundles/com.zeligsoft.domain.dds4ccm/models/DDS4CCM.uml
The validation rule "deployment_parts_with_local_interface_collocation"
in DDS4CCM refers to the "ComponentDeploymentPart" in the ZMLMM package.
Therefore, it is necessary to import the ZMLMM package in DDS4CCM for
the proper loading of this validation constraint.
> Import ZMLMM package in the DDS4CCM model

- bundles/com.zeligsoft.domain.ngc.ccm.descriptorgeneration/src/com/zeligsoft/domain/ngc/ccm/descriptorgeneration/DDS4CCMXtendUtils.java
- bundles/com.zeligsoft.domain.ngc.ccm.descriptorgeneration/template/mainTransformAxcioma.ext
Improvements with this fix:
1. For multiple connections from a single port in a component, we used
to generate multiple connector instances. This fix changes it with the
generation of one connector instance per non-local interface port. If
any of the connected components are not deployed, RegisterNaming tag and
external connection entry tags are generated in the connector instance
associated with the port.
2. This fix provides support for the generation of unconnected ports.
This closes issue#45.
3. Also, this fixes issue#50 which mentions the generation of the
same names for multiple connector instances.
4. Code for generation is reorganized. This now follows a tree
structure: while visiting a deployed component, we visit all the
non-local interface ports of the component and create all …
> Generate for unconnected ports, fix 1-to-many connections in a port,  and code reorganization

- bundles/com.zeligsoft.domain.ngc.ccm.descriptorgeneration/template/mainTransformAxcioma.ext
For retrieving the connected parts from a given port, deployed port property is used for retrieving the parent ComponentDeploymentPart. This ensures that we have the correct ComponentDeploymentPart from the deployment editor for deciding which port instances we need to make connections with. 
This fixes issue#6.
> Fix erroneous connection generation for unconnected ports in an assembly instance

- .travis.yml
- bundles/com.zeligsoft.base.zdl/src/com/zeligsoft/base/zdl/listeners/ZDLElementTypeResourceSetListener.java
- bundles/com.zeligsoft.domain.cbdds.architecture/build.properties
- bundles/com.zeligsoft.domain.dds4ccm.idlimport/src/com/zeligsoft/domain/dds4ccm/idlimport/ImportOrganizer.java
- bundles/pom.xml
- features/com.zeligsoft.base-feature/feature.xml
- features/com.zeligsoft.cx-feature/feature.xml
- features/com.zeligsoft.domain.ngc.ccm-feature/feature.xml
- features/com.zeligsoft.domain.ngc.ccm.axcioma-feature/feature.xml
- features/com.zeligsoft.domain.omg.ccm-feature/feature.xml
- readme.md
- releng/com.zeligsoft.dds4ccm.configuration/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/category.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/category.xml
The update is done by considering the following changes in the project:
- Removal of 7 plugins
- Inclusion of 1 new plugin
- Removal of all dependencies to the IBM artifacts
- Inclusion of dependencies to the open-source Papyrus platform
- Inclusion of upgraded version for dependencies on the modeling tools
Also, the readme file has been changed accordingly.
> Update build configuration for CX4CBDDS project for Papyrus

- .travis.yml
- releng/com.zeligsoft.dds4ccm.update.atcd/rpm_build/zeligsoftCX_atcd.spec
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
The 'rpmbuild' commands are updated by passing two new parameters: Travis commit hash and tag values. Depending on the availability of these parameters, the release field is updated in the spec files.
This closes #54.
> Include git hash and tag values to the generated rpm names

- bundles/com.zeligsoft.domain.ngc.ccm.descriptorgeneration/template/mainTransformAxcioma.ext
Remote connection from a server-side connector instance is not generated
anymore. Also, for a remote connection from a client-side connector
instance, 'location' element of 'externalReference' now points to the
value of the registerNaming property of the remotely connected server
connector instance.
> Fix generation for remote connections

- bundles/com.zeligsoft.domain.ngc.ccm.descriptorgeneration/template/mainTransformAtcd.ext
Corrected syntax of an xtend function with no meaningful body.
Fixes # 66
> Correct syntax for an empty Xtend function

- bundles/com.zeligsoft.domain.ngc.ccm.descriptorgeneration/template/mainTransformAxcioma.ext
Closes #69
Characteristics of generated async/AMI connections
- one connector (usually CORBA) per provides port (facet)
- one connector (AMI) in the client process (uses port side), per connection to a provides port
- on the client side the sendc\__receptport_ is a SimplexReceptacle, and connects to the client-side AMI connector's `ami4ccm_port_ami4ccm_provides` port.
- on the client side, the _receptport_ is a MultiplexReceptacle, and connects to the client-side AMI connector's `ami4ccm_port_ami4ccm_sync_provides` port.
Characteristics of generated sync/CORBa connections
- one connector (CORBA) per provides port (facet)
- one connector (CORBA) in the client process (users port side), per connection to a provides port
- the client side uses/receptacle is a MultiplexReceptacle, and …
> Create one AXCIOMA client-side connector per server connection

- bundles/com.zeligsoft.domain.ngc.ccm.descriptorgeneration/template/mainTransformAxcioma.ext
If two components each have a facet (provides) port and a receptacle (uses) port, and the facets and receptacles are connected, then the generated CDP
will have a missing xmi:idref in one of the <instance>
tags have an empty xmi:idref field.
Changes:
- mainTransformAxcioma is no longer a ‘create’ function
- it delegates new create: findOrCreateDeploymentPlan.
- one ‘visit’ overload is no longer a create function.
- it delegates new create: findOrCreateComponentInstance
- For the affected code, replaced passing of output model DeploymentPlan with calls to findOrCreateDeploymentPlan.
- replaced searches of output model with calls to create functions.
> Missing xmi:idref in CDP with 2-way connections

- .travis.yml
- bundles/com.zeligsoft.domain.ngc.ccm.descriptorgeneration/template/mainTransformAxcioma.ext
- releng/com.zeligsoft.dds4ccm.update.axcioma/category.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
CPD generation. Merges the following to papyrus branch: #70, #71 and #72 
Closes #73 
RPM now references correct IUs, version 2.0.0, and /opt/Papyrus. Update site includes missing plug-ins & features.
Closes #75 
Papyrus build now only builds an AXCIOMA update site and RPM. Note that this update site still allows for ATCD modelling.
> Update CDP generation; correct RPM; fix update site dependencies

- releng/com.zeligsoft.dds4ccm.update.axcioma/category.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
- added org.eclipse.xtext.xbase as a dependency
- corrected RPM to use /opt/Papyrus/papyrus as the eclipse target and executable.
Signed-off-by: Paul Elder <11318425+elder4p@users.noreply.github.com>
> Correctly install RPM against Papyrus RCP app

- bundles/com.zeligsoft.domain.dds4ccm.ui/plugin.xml
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/providers/ResolvingUMLFilteredLabelProvider.java
- bundles/com.zeligsoft.domain.dds4ccm/META-INF/MANIFEST.MF
- bundles/com.zeligsoft.domain.dds4ccm/plugin.xml
Added a label provider which resolves EObject proxies and delegates to
the UMLFilteredLabelProvider who knows how to deal with UML models
including stereotypes.
> Issue 132: NPEs popup in Model Differences view

- bundles/com.zeligsoft.domain.dds4ccm.ui/plugin.xml
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/services/CoreMultiDiagramEditorService.java
Fixes #136.
Added a dummy IMultiDiagramEditor service to the Papyrus ServiceRegistry as is required by some parts of PapyrusCompare (e.g. when creating/refreshing DiffMergeViewers).
> Issue #136: Resolving Missing service when comparing diagram elements

- bundles/com.zeligsoft.domain.dds4ccm.ui/plugin.xml
By ensuring that the new service has lower priority than the service provided by Papyrus, the later will be registered over the former when opening a Papyrus Model.
The new service will only be registered in the context of a Diff/Merge with Papyrus Compare.
> Issue #150: Log entry introduced for org.eclipse.papyrus.infra.ui.editor.IMultiDiagramEditor

- bundles/com.zeligsoft.domain.ngc.ccm.generator/src/com/zeligsoft/domain/ngc/ccm/generator/xtend/includes.ext
> Issue #63: GIS Templated Connectors cannot be typed with a Struct, only

- bundles/com.zeligsoft.domain.zml/src/com/zeligsoft/domain/zml/util/ZDeploymentUtil.java
> Issue #249: Accidental dragging of assemblies into themselves does not

- ddk/com.zeligsoft.ddk.tools/OSGI-INF/l10n/bundle.properties
- ddk/com.zeligsoft.ddk.tools/plugin.xml
- ddk/com.zeligsoft.ddk.tools/src/com/zeligsoft/ddk/tools/ui/internal/handlers/AbsorbMergedPackagesHandler.java
- ddk/com.zeligsoft.ddk.tools/src/com/zeligsoft/ddk/tools/ui/internal/handlers/AbsorbMergedPackagesWorker.java
- ddk/com.zeligsoft.ddk.tools/src/com/zeligsoft/ddk/tools/ui/internal/handlers/Messages.java
- ddk/com.zeligsoft.ddk.tools/src/com/zeligsoft/ddk/tools/ui/internal/handlers/messages.properties
- new eclipse command
- new command handler implementation
- new eclipse menu contribution
- most business logic is in AbsorbMergedPackagesWorker.java
- separate worker allows for re-use in older Eclipse 'action sets'
> Issue #295: Add 'Absorb Merged Packages' to 'ZDL Tools' popup

- papyrus-patch/v4.4.0/site-papyrus-patch/site.xml
- readme.md
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
- revert RPM changes. Patch should be installed separately, when Papyrus is installed.
- correct text in patch P2 repo (non-functional change)
- update root readme.md to explain patching process
Note: You can download the built artifacts from the attached build (the `papyrus_v440_patch_*.zip`, and the RPM `cx-axioma-*.rpm`). For convenience, the following command will install the patch into a Papyrus located in `<papyrus-loc>`, and with the patch located in `<patch-loc>` with version `<version>`:
```
sudo <papyrus-loc>/papyrus -application org.eclipse.equinox.p2.director -nosplash \
-installIU com.zeligsoft.papyruspatch.feature.group \
-repository jar:file:<patch-loc>/papyrus_v440_patch_2.1.0.<version>.zip\!/  \
-vmargs -Xmx1024m
```
To uninstall the patch feature, use:
```
sudo …
```
> Issue #308: Do not include papyrus patch in RPMs

- releng/com.zeligsoft.papyruscx.targetdefinition/papyruscx-release.target
- releng/com.zeligsoft.papyruscx.targetdefinition/papyruscx-release.tpd
This commit simply adds the Papyrus SDK to the target platform, as well as a missing dependency to org.eclipse.emf.mwe2.lib required by com.zeligsoft.domain.omg.corba.dsl.
Furthermore, it synchronizes the .tpd and .target files.
> Papyrus target update

- bundles/pom.xml
- ddk/pom.xml
- features/pom.xml
- papyrus-patch/v4.4.0/pom.xml
- pom.xml
- releng/com.zeligsoft.ddk.update/pom.xml
- releng/com.zeligsoft.dds4ccm.configuration/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/rpm_build/zeligsoftCX_atcd.spec
- releng/com.zeligsoft.dds4ccm.update.axcioma/pom.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
- releng/pom.xml
- updated all versions to 2.1.1, except this for the papyrus 4.4.0 patch, which remains at 2.1.0
- Kept patch at 2.1.0 because it is very unlikely to change
The build now creates the following 2.1.1 artifacts:
```
./releng/com.zeligsoft.ddk.update/target/com.zeligsoft.ddk.update-2.1.1-SNAPSHOT.zip
./releng/com.zeligsoft.ddk.update/target/ddk_2.1.1.v202204071941.zip
./releng/com.zeligsoft.dds4ccm.update.atcd/target/com.zeligsoft.dds4ccm.update.atcd-2.1.1-SNAPSHOT.zip
./releng/com.zeligsoft.dds4ccm.update.atcd/target/dds4ccm_atcd_2.1.1.v202204071941.zip
./releng/com.zeligsoft.dds4ccm.update.axcioma/target/dds4ccm_axcioma_2.1.1.v202204071941.zip
./releng/com.zeligsoft.dds4ccm.update.axcioma/target/com.zeligsoft.dds4ccm.update.axcioma-2.1.1-SNAPSHOT.zip
```
The build continues to create these …
> Issue 383: Updated streamsv2.1.x-maintenance versions to 2.1.1

- bundles/com.zeligsoft.base/src/com/zeligsoft/base/util/JavaReflectionUtil.java
- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/.classpath
- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/.project
- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/.settings/org.eclipse.jdt.core.prefs
- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/META-INF/MANIFEST.MF
- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/build.properties
- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/plugin.properties
- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/plugin.xml
- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/schema/com.zeligsoft.domain.dds4ccm.ui.errorhandlers.undesirableExceptions.exsd
- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/schema/undesirableExceptions.exsd
- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/src/com/zeligsoft/domain/dds4ccm/ui/errorhandlers/Activator.java
- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/src/com/zeligsoft/domain/dds4ccm/ui/errorhandlers/statushandlers/FilteringStatusHandler.java
- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/src/com/zeligsoft/domain/dds4ccm/ui/errorhandlers/statushandlers/UndesirableException.java
- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/src/com/zeligsoft/domain/dds4ccm/ui/errorhandlers/statushandlers/UndesirableExceptionRegistry.java
- bundles/pom.xml
- features/com.zeligsoft.domain.ngc.ccm-feature/feature.xml
- features/com.zeligsoft.domain.ngc.ccm.axcioma-feature/feature.xml
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/plugin_customization.ini
This pull request introduces a custom error handler to deal with "undesirable exceptions" as described in Issue #390.
It provides a new status handler called a "FilteringStatusHandler", associated with the new Papyrus-CX product, overriding the default handler.
The new filtering status handler contains a list of "undesirable exceptions" (registered via a new extension point described below). Whenever an exception is thrown and the status handler is triggered (its 'handle' method is invoked), it determines if the cause of the exception matches one of the undesirable exceptions, and if this is the case, it simply logs it and returns, inhibiting any handling by the standard error handler, including pop-ups. Otherwise, if it doesn't match any of the undesirable exceptions registered, it …
> Papyrus Issue #390

- bundles/com.zeligsoft.domain.dds4ccm.ddsdcpsconnector/plugin.xml
- bundles/com.zeligsoft.domain.idl3plus.ui/src/com/zeligsoft/domain/idl3plus/ui/providers/IDL3PlusPropertyContentProvider.java
- bundles/com.zeligsoft.domain.idl3plus/META-INF/MANIFEST.MF
- bundles/com.zeligsoft.domain.idl3plus/schema/ddsmodellibrary.exsd
- bundles/com.zeligsoft.domain.idl3plus/src/com/zeligsoft/domain/idl3plus/connectorregistry/ConnectorRegistry.java
- bundles/com.zeligsoft.domain.idl3plus/src/com/zeligsoft/domain/idl3plus/utils/IDL3PlusUtil.java
- bundles/com.zeligsoft.domain.ngc.ccm.descriptorgeneration/src/com/zeligsoft/domain/ngc/ccm/descriptorgeneration/utils/FilterUtil.java
- bundles/com.zeligsoft.domain.ngc.ccm.descriptorgeneration/template/mainTransformAxcioma.ext
- bundles/com.zeligsoft.domain.omg.ccm.descriptorgenerator/src/com/zeligsoft/domain/omg/ccm/descriptorgenerator/utils/cdpgenerator.ext
This commit uses the extension point to filter properties in the Properties section
of a connector and to filter properties in the descriptor generator.
Signed-off-by: Ernesto Posse <ernesto.posse@lumenix.com>
> Issue #397: Introduced filteredProperty attributes to the model_library_configuration extension point

- bundles/com.zeligsoft.base/src/com/zeligsoft/base/util/JavaReflectionUtil.java
The new status/exception handler causes an NPE when it finds some "wrapped" exceptions that do not have a canonical name. This change ensures that that case is handled without raising an NPE.
(This was discovered while working with the DDK, and selecting the "Add CX" menu option from the context menu when selecting an element of a meta-model like DDS4CCM itself.
Signed-off-by: Ernesto Posse <ernesto.posse@lumenix.com>
> Fix NPE caused by Exception Handler when dealing with wrapped exceptions

- .github/workflows/linux_build.yml
- bundles/pom.xml
- ddk/pom.xml
- features/pom.xml
- papyrus-patch/v4.4.0/feature-com.zeligsoft.papyruspatch/feature.xml
- papyrus-patch/v4.4.0/pom.xml
- papyrus-patch/v4.4.0/site-papyrus-patch/pom.xml
- papyrus-patch/v4.4.0/site-papyrus-patch/site.xml
- pom.xml
- releng/com.zeligsoft.ddk.update/pom.xml
- releng/com.zeligsoft.dds4ccm.configuration/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/rpm_build/zeligsoftCX_atcd.spec
- releng/com.zeligsoft.dds4ccm.update.axcioma/pom.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
- releng/pom.xml
Setup up 2.1.2 builds on streams/v2.1.x-maintenance branch.
> Issue #419: update 2.1.x maintenance branch to 2.1.2

- bundles/com.zeligsoft.cx.codegen/src/codegen/debug.ext
- bundles/com.zeligsoft.cx.codegen/src/com/zeligsoft/cx/codegen/internal/OawDebug.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/filters/CXModelFilter.java
- bundles/com.zeligsoft.domain.idl3plus/src/com/zeligsoft/domain/idl3plus/utils/IDL3PlusUtil.java
- bundles/com.zeligsoft.domain.ngc.ccm.descriptorgeneration/template/mainTransformAxcioma.ext
This PR addresses Issue #445 which happens whenever there is a part in an assembly with an unconnected port and there is also a (DataSpace) connector. The solution is essentially to ignore these ports in the getDataSpaceFromPerPort function.
> Papyrus Issue #445
