- .travis.yml
- releng/com.zeligsoft.dds4ccm.update.atcd/rpm_build/zeligsoftCX_atcd.spec
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
Include RPM generation (#38) into master, and release as part of 1.6.0 build.
> Integrate RPM generation into build

- bundles/pom.xml
- features/pom.xml
- pom.xml
- releng/com.zeligsoft.dds4ccm.configuration/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/rpm_build/zeligsoftCX_atcd.spec
- releng/com.zeligsoft.dds4ccm.update.axcioma/pom.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
- releng/pom.xml
Post 1.6.0 release, update build artifacts so that subsequent builds will have a 1.6.1 version
> Update build version to 1.6.1

- bundles/com.zeligsoft.domain.dds4ccm/src/com/zeligsoft/domain/dds4ccm/constraints/java/DeploymentPartsWithLocalInterfaceCollocationConstraint.java
For multiple instances of an assembly deployed as parts of a root
assembly, modelElement of the same component owned by the multiple
assembly instances are not unique. Therefore, it is necessary to make
comparison with a DeploymentPart in the 'getDeploymentTarget' method,
instead of comparing with a CCMpart for retrieving the correct
DeploymentPart instance.
Also, modelElement of a DeploymentPart representing an assembly can be
either a CCMComponent or a CCMPart. A correction related to this is made
in 'getUsesDelegationPartInfo' method.
This fixes issue#49.
> Retrieve deployment target that matches a DeploymentPart, not a CCMPart

- readme.md
> Updated link for AXCIOMA to www.axcioma.org

- releng/com.zeligsoft.dds4ccm.update.axcioma/category.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
- axcioma RPM now installs for CDT
- Update site now includes all CDT required dependencies
Addresses #75 
Signed-off-by: Paul Elder <11318425+elder4p@users.noreply.github.com>
> Include CDT in AXCIOMA RPM

- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/filters/CXModelFilter.java
- bundles/com.zeligsoft.domain.omg.ccm.ui/src/com/zeligsoft/domain/omg/ccm/ui/actions/AddAssemblyImplementation.java
- bundles/com.zeligsoft.domain.omg.ccm.ui/src/com/zeligsoft/domain/omg/ccm/ui/actions/AddHomeToComponentAction.java
- bundles/com.zeligsoft.domain.omg.ccm.ui/src/com/zeligsoft/domain/omg/ccm/ui/actions/AddMonolithicImplementation.java
Component
Fix issues creating elements
> Issue #95: Unable to create Assembly or Monolithic Implementation from

- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/filters/CXModelFilter.java
instance values to match the same behaviour as RSA
> Issue 101: Do not hide _defaultInstance and the package containing the

- bundles/com.zeligsoft.cx.ui/src/com/zeligsoft/cx/ui/providers/ZDLElementContentProvider.java
> Issue#98: Browse element does not work.

- releng/com.zeligsoft.dds4ccm.configuration/pom.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/category.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
Added installIU and uninstallIU clauses to RPM spec to install/uninstall Papyrus Compare
> Updated RPM spec to install Papyrus Compare

- bundles/com.zeligsoft.cx.ui.properties/src/com/zeligsoft/cx/ui/properties/pages/CXPropertyCollectionPage.java
- bundles/com.zeligsoft.cx.ui.properties/src/com/zeligsoft/cx/ui/properties/pages/CXPropertyEditingSupport.java
- bundles/com.zeligsoft.cx.ui.properties/src/com/zeligsoft/cx/ui/properties/utils/CXPropertiesWidgetFactory.java
> Issue#143: Creating a primitive type value in multivalued property page

- bundles/com.zeligsoft.domain.dds4ccm.ui/plugin.xml
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/services/CustomProfileDefinitionService.java
Changes the error messages to warnings
> Fixes #131 by overriding the ProfileDefinitionService

- bundles/com.zeligsoft.domain.dds4ccm.ui/plugin.xml
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/strategies/CompositeDiagramSemanticChildrenStrategy.java
> Issue#117: Outer ports disappear when attempting to make connection from

- bundles/com.zeligsoft.base.ui/src/com/zeligsoft/base/ui/ZeligsoftAbstractUIPlugin.java
- bundles/com.zeligsoft.base/src/com/zeligsoft/base/ZeligsoftAbstractPlugin.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/actions/CreateCXModelFromUMLModelHandler.java
- releng/com.zeligsoft.dds4ccm.update.axcioma/category.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
This updates the rpm spec file and the category.xml for the axcioma update site to include all required dependencies.
> Issue #193: Papyrus rpm deps

- releng/.project
- releng/com.zeligsoft.papyruscx.targetdefinition/.project
- releng/com.zeligsoft.papyruscx.targetdefinition/papyruscx-release.target
- releng/com.zeligsoft.papyruscx.targetdefinition/papyruscx-release.tpd
This pull request adds a new TPD file defining the target platform for Papyrus CX.
> Papyrus targetdef

- bundles/com.zeligsoft.domain.dds4ccm/META-INF/MANIFEST.MF
- bundles/com.zeligsoft.domain.dds4ccm/plugin.xml
- bundles/com.zeligsoft.domain.dds4ccm/src/com/zeligsoft/domain/dds4ccm/utils/AXCIOMAMatchEngineFactory.java
- releng/.project
- releng/com.zeligsoft.papyruscx.targetdefinition/.project
- releng/com.zeligsoft.papyruscx.targetdefinition/papyruscx-release.target
- releng/com.zeligsoft.papyruscx.targetdefinition/papyruscx-release.tpd
This commit fixes issue #156 which in turn resolves issue #202.
> Fix for issues #202 and  #156

- releng/com.zeligsoft.dds4ccm.configuration/pom.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/category.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
> Issue 170: Integrating build of EMF Compare fork

- bundles/com.zeligsoft.domain.dds4ccm.ui/plugin.xml
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/actions/ExportToUMLActionDelegate.java
Export to UML menu to export EMX file to UML + diagram layout info
> Issue #219: Export UML with diagram layout

- bundles/com.zeligsoft.cx.deployment.treeeditor/src/com/zeligsoft/cx/deployment/treeeditor/providers/LeftTreeLabelProvider.java
- bundles/com.zeligsoft.cx.deployment.treeeditor/src/com/zeligsoft/cx/deployment/treeeditor/providers/RightTreeLabelProvider.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/plugin.xml
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/providers/DDS4CCMCustomPropertySectionProvider.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/providers/ResolvingUMLFilteredLabelProvider.java
- bundles/com.zeligsoft.domain.ngc.ccm.descriptorgeneration/template/cdd.ext
> Issue #228: Generate descriptors does not generate correct node name in

- bundles/com.zeligsoft.domain.dds4ccm.ui/META-INF/MANIFEST.MF
- bundles/com.zeligsoft.domain.dds4ccm.ui/plugin.xml
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/actions/ResetCompartmentFilterAction.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/actions/ResetCompartmentFilterActionHandler.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/strategies/ComponentPartCompartmentChildrenStrategy.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/strategies/CompositeDiagramSemanticChildrenStrategy.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/stylesheets/cxstyle.css
from diagram or internal structure of CCMComponent
> Issue #257: Add reset compartment filter menu & hide attributes/comments

- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/filters/CXModelFilter.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/internal/filters/CBDDSPropertiesFilter.java
> Issue #270: Fix model explorer filter to show all referenced models when

- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/actions/ExportToUMLActionDelegate.java
> Issue #276: Open confirmation dialog if at least one of the UML output

- releng/com.zeligsoft.dds4ccm.configuration/pom.xml
Updating update-site dependencies URLs to https.
> Papyrus Issue #296

- bundles/com.zeligsoft.base.ui/src/com/zeligsoft/base/ui/utils/BaseUIUtil.java
- bundles/com.zeligsoft.cx.codegen.ui/src/com/zeligsoft/cx/codegen/ui/actions/AbstractTransformAction.java
- bundles/com.zeligsoft.cx.codegen.ui/src/com/zeligsoft/cx/codegen/ui/l10n/Messages.java
- bundles/com.zeligsoft.cx.codegen.ui/src/com/zeligsoft/cx/codegen/ui/l10n/messages.properties
- bundles/com.zeligsoft.cx.codegen.ui/src/com/zeligsoft/cx/codegen/ui/transformregistry/WorkflowEntry.java
This commit implements reporting of generation results on the console and the log. It works for any transformation registered, including generation of descriptors, IDL and UML (from the Generate menu).
Signed-off-by: Ernesto Posse <eposse@gmail.com>
> Issue #286: Report generation results in the console and the log

- bundles/com.zeligsoft.base.ui/src/com/zeligsoft/base/ui/utils/BaseUIUtil.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/META-INF/MANIFEST.MF
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/Activator.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/internal/MigrationChecker.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/l10n/Messages.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/l10n/Messages.properties
This pull request addresses Issue #287
> Papyrus Issue #287

- bundles/com.zeligsoft.domain.dds4ccm.idlimport/template/ddsIdl3Import.ext
- bundles/com.zeligsoft.domain.dds4ccm.idlimport/template/importOrganizer.ext
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/l10n/Messages.properties
- bundles/com.zeligsoft.domain.omg.ccm.idlimport/template/idl3Import.ext
- bundles/com.zeligsoft.domain.omg.corba.idlimport/src/com/zeligsoft/domain/omg/corba/idlimport/IDLPreprocessor.java
- bundles/com.zeligsoft.domain.omg.corba.idlimport/src/com/zeligsoft/domain/omg/corba/idlimport/XtendUtils.java
- bundles/com.zeligsoft.domain.omg.corba.idlimport/template/idlimport.ext
Fixed a couple of issues with IDLImport.
1. Place Union under the destination package with other elements.
2. Fix CXConstant import issue
> Issue #303: Fix import issue with Union

- .github/workflows/linux_build.yml
- copy release artifacts back to GitHub
> Publish artifacts on master release build

- bundles/com.zeligsoft.cx.codegen.ui/src/com/zeligsoft/cx/codegen/ui/actions/AbstractTransformAction.java
- bundles/com.zeligsoft.cx.codegen.ui/src/com/zeligsoft/cx/codegen/ui/transformregistry/TransformRegistry.java
- bundles/com.zeligsoft.cx.codegen/META-INF/MANIFEST.MF
- bundles/com.zeligsoft.cx.codegen/src/com/zeligsoft/cx/codegen/internal/OawDebug.java
- bundles/com.zeligsoft.domain.ngc.ccm.generator/src/com/zeligsoft/domain/ngc/ccm/generator/xtend/debugUtils.ext
- bundles/com.zeligsoft.domain.ngc.ccm.generator/src/com/zeligsoft/domain/ngc/ccm/generator/xtend/mainTransformAtcd.ext
- bundles/com.zeligsoft.domain.ngc.ccm.generator/src/com/zeligsoft/domain/ngc/ccm/generator/xtend/mainTransformAxcioma.ext
- bundles/com.zeligsoft.domain.ngc.ccm.generator/src/com/zeligsoft/domain/ngc/ccm/utils/Copier.java
- bundles/com.zeligsoft.domain.ngc.ccm.generator/src/com/zeligsoft/domain/ngc/ccm/utils/DebugUtils.java
Minor cleanup.
Signed-off-by: Ernesto Posse <eposse@gmail.com>
> Issue #286: Clean up and disable workflow debug output

- bundles/pom.xml
- features/pom.xml
- pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/rpm_build/zeligsoftCX_atcd.spec
- releng/com.zeligsoft.dds4ccm.update.axcioma/pom.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
- releng/pom.xml
- post release version change from 1.6.1 to 1.6.2
Signed-off-by: Paul Elder <11318425+elder4p@users.noreply.github.com>
> Update 'master' branch to CX version 1.6.2

- bundles/pom.xml
- ddk/pom.xml
- features/pom.xml
- papyrus-patch/v4.4.0/pom.xml
- papyrus-patch/v4.4.0/site-papyrus-patch/pom.xml
- pom.xml
- releng/com.zeligsoft.ddk.update/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/rpm_build/zeligsoftCX_atcd.spec
- releng/com.zeligsoft.dds4ccm.update.axcioma/pom.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
- releng/pom.xml
- post release version update from 2.1.0 to 2.2.0
Signed-off-by: Paul Elder <11318425+elder4p@users.noreply.github.com>
> Update 'papyrus' branch to version 2.2.0

- bundles/com.zeligsoft.base.zdl/src/com/zeligsoft/base/zdl/util/ZDLUtil.java
- bundles/com.zeligsoft.cx.ui.properties/src/com/zeligsoft/cx/ui/properties/CXPropertyDescriptor.java
- bundles/com.zeligsoft.domain.dds4ccm.ui/META-INF/MANIFEST.MF
- bundles/com.zeligsoft.domain.dds4ccm.ui/elementtypes/DDS4CCM_ui.elementtypesconfigurations
- bundles/com.zeligsoft.domain.dds4ccm.ui/src/com/zeligsoft/domain/dds4ccm/ui/edithelpers/InterfacePortEditHelperAdvice.java
- bundles/com.zeligsoft.domain.dds4ccm/profiles/DDS4CCM.ztooling
- bundles/com.zeligsoft.domain.omg.ccm/models/CCM.zdlgen
- bundles/com.zeligsoft.domain.omg.corba/models/CORBADomain.zdlgen
- bundles/com.zeligsoft.domain.zml/src/com/zeligsoft/domain/zml/util/WorkerFunctionRepair.java
> Issue #356: Hide isAsynchronous from Interface and make isAsynchronous

- bundles/com.zeligsoft.domain.idl3plus/src/com/zeligsoft/domain/idl3plus/constraints/java/NamespaceDistinctMembersConstraint.java
- bundles/com.zeligsoft.domain.zml/src/com/zeligsoft/domain/zml/util/ZDeploymentUtil.java
> Issue #396: Issue with CDD creation of multiple domains within a single

- .github/workflows/linux_build.yml
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.product/papyrus-cx-axcioma.product
- releng/com.zeligsoft.papyrus-cx.axcioma.targetdefinition/papyrus-cx-axcioma-release.target
- releng/com.zeligsoft.papyrus-cx.axcioma.targetdefinition/papyrus-cx-axcioma-release.tpd
Signed-off-by: Ernesto Posse <ernesto.posse@lumenix.com>
> Added XML editor to RCP

- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.product/papyrus-cx-axcioma.product
Updated the .product so that the p2 reconciler that scans the dropins folder automatically starts.
> Configured the RCP product so that the p2 dropins reconciler auto-starts

- bundles/com.zeligsoft.domain.dds4ccm.ui.errorhandlers/plugin.xml
Signed-off-by: Ernesto Posse <ernesto.posse@lumenix.com>
> Issue #426: Added new undesirable exception filter (NPE on markSaveLocation)

- .github/workflows/linux_build.yml
- bundles/pom.xml
- ddk/pom.xml
- features/pom.xml
- papyrus-patch/v4.4.0/feature-com.zeligsoft.papyruspatch/category.xml
- papyrus-patch/v4.4.0/feature-com.zeligsoft.papyruspatch/feature.xml
- papyrus-patch/v4.4.0/pom.xml
- papyrus-patch/v4.4.0/site-papyrus-patch/pom.xml
- papyrus-patch/v4.4.0/site-papyrus-patch/site.xml
- papyrus-patch/v4.8.0/feature-com.zeligsoft.papyruspatch/category.xml
- papyrus-patch/v4.8.0/feature-com.zeligsoft.papyruspatch/feature.xml
- papyrus-patch/v4.8.0/pom.xml
- papyrus-patch/v4.8.0/site-papyrus-patch/pom.xml
- papyrus-patch/v4.8.0/site-papyrus-patch/site.xml
- pom.xml
- releng/com.zeligsoft.ddk.update/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/rpm_build/zeligsoftCX_atcd.spec
- releng/com.zeligsoft.dds4ccm.update.axcioma/pom.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.feature/feature.xml
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.product/pom.xml
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.product/rpm_build/papyrus-cx-axcioma.spec
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/META-INF/MANIFEST.MF
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/about.mappings
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/about.properties
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/plugin.properties
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/plugin.xml
- releng/pom.xml
Bump from 2.2.0 to 2.2.1. Part of issue #434
> Version bump streams/v2.2.x-maintenance to 2.2.1

- .github/workflows/linux_build.yml
- bundles/pom.xml
- ddk/pom.xml
- features/pom.xml
- papyrus-patch/v4.4.0/feature-com.zeligsoft.papyruspatch/category.xml
- papyrus-patch/v4.4.0/feature-com.zeligsoft.papyruspatch/feature.xml
- papyrus-patch/v4.4.0/pom.xml
- papyrus-patch/v4.4.0/site-papyrus-patch/pom.xml
- papyrus-patch/v4.4.0/site-papyrus-patch/site.xml
- papyrus-patch/v4.8.0/feature-com.zeligsoft.papyruspatch/category.xml
- papyrus-patch/v4.8.0/feature-com.zeligsoft.papyruspatch/feature.xml
- papyrus-patch/v4.8.0/pom.xml
- papyrus-patch/v4.8.0/site-papyrus-patch/pom.xml
- papyrus-patch/v4.8.0/site-papyrus-patch/site.xml
- pom.xml
- releng/com.zeligsoft.ddk.update/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/rpm_build/zeligsoftCX_atcd.spec
- releng/com.zeligsoft.dds4ccm.update.axcioma/pom.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.feature/feature.xml
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.product/pom.xml
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.product/rpm_build/papyrus-cx-axcioma.spec
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/META-INF/MANIFEST.MF
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/about.mappings
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/about.properties
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/plugin.properties
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/plugin.xml
- releng/pom.xml
> Version bump papyrus branch to 2.3.0

- bundles/com.zeligsoft.domain.dds4ccm.ui.compare/.classpath
- bundles/com.zeligsoft.domain.dds4ccm.ui.compare/.project
- bundles/com.zeligsoft.domain.dds4ccm.ui.compare/.settings/org.eclipse.jdt.core.prefs
- bundles/com.zeligsoft.domain.dds4ccm.ui.compare/META-INF/MANIFEST.MF
- bundles/com.zeligsoft.domain.dds4ccm.ui.compare/build.properties
- bundles/com.zeligsoft.domain.dds4ccm.ui.compare/plugin.properties
- bundles/com.zeligsoft.domain.dds4ccm.ui.compare/plugin.xml
- bundles/com.zeligsoft.domain.dds4ccm.ui.compare/src/com/zeligsoft/domain/dds4ccm/ui/compare/Activator.java
- bundles/com.zeligsoft.domain.dds4ccm.ui.compare/src/com/zeligsoft/domain/dds4ccm/ui/compare/internal/contentmergeviewer/accessor/factory/impl/DDS4CCMContainementReferenceChangeAccessorFactory.java
- bundles/com.zeligsoft.domain.dds4ccm.ui.compare/src/com/zeligsoft/domain/dds4ccm/ui/compare/internal/contentmergeviewer/accessor/factory/impl/DDS4CCMMatchAccessorFactory.java
- bundles/com.zeligsoft.domain.dds4ccm.ui.compare/src/com/zeligsoft/domain/dds4ccm/ui/compare/internal/contentmergeviewer/accessor/impl/DDS4CCMContainmentReferenceChangeAccessorImpl.java
- bundles/com.zeligsoft.domain.dds4ccm.ui.compare/src/com/zeligsoft/domain/dds4ccm/ui/compare/internal/contentmergeviewer/accessor/impl/DDS4CCMMatchAccessor.java
- bundles/pom.xml
- features/com.zeligsoft.domain.ngc.ccm.axcioma-feature/feature.xml
This PR overrides EMF Compare behaviour to simplify the items shown in the Content Merge Viewer so that there is no longer any performance degradation.
> Issue #415: Fix diff navigation performance

- bundles/com.zeligsoft.domain.dds4ccm.compare/.classpath
- bundles/com.zeligsoft.domain.dds4ccm.compare/.project
- bundles/com.zeligsoft.domain.dds4ccm.compare/.settings/org.eclipse.jdt.core.prefs
- bundles/com.zeligsoft.domain.dds4ccm.compare/META-INF/MANIFEST.MF
- bundles/com.zeligsoft.domain.dds4ccm.compare/build.properties
- bundles/com.zeligsoft.domain.dds4ccm.compare/plugin.properties
- bundles/com.zeligsoft.domain.dds4ccm.compare/plugin.xml
- bundles/com.zeligsoft.domain.dds4ccm.compare/src/com/zeligsoft/domain/dds4ccm/compare/Activator.java
- bundles/com.zeligsoft.domain.dds4ccm.compare/src/com/zeligsoft/domain/dds4ccm/compare/DDS4CCMReferenceChangeMerger.java
- bundles/com.zeligsoft.domain.dds4ccm.ui.compare/plugin.properties
- bundles/pom.xml
- features/com.zeligsoft.domain.ngc.ccm.axcioma-feature/feature.xml
This PR overrides code in ReferenceChangeMerger which is the cause of the exception described in Issue #444.
> Issue #444: Overriding EMF Compare UML ReferenceChangeMerger

- bundles/com.zeligsoft.cx.codegen/src/com/zeligsoft/cx/codegen/internal/OawDebug.java
- bundles/com.zeligsoft.domain.idl3plus/src/com/zeligsoft/domain/idl3plus/utils/IDL3PlusXtendUtils.java
- bundles/com.zeligsoft.domain.ngc.ccm.descriptorgeneration/template/mainTransformAxcioma.ext
- bundles/com.zeligsoft.domain.omg.ccm.descriptorgenerator/src/com/zeligsoft/domain/omg/ccm/descriptorgenerator/utils/CDPXtendUtils.java
- bundles/com.zeligsoft.domain.omg.ccm.descriptorgenerator/src/com/zeligsoft/domain/omg/ccm/descriptorgenerator/utils/cdpgenerator.ext
- bundles/com.zeligsoft.domain.omg.ccm.descriptorgenerator/src/com/zeligsoft/domain/omg/ccm/descriptorgenerator/utils/util.ext
Generate separate instance per port connected to a DataSpace
> Papyrus Issue #463

- bundles/pom.xml
- ddk/pom.xml
- features/pom.xml
- papyrus-patch/v4.4.0/feature-com.zeligsoft.papyruspatch/category.xml
- papyrus-patch/v4.4.0/feature-com.zeligsoft.papyruspatch/feature.xml
- papyrus-patch/v4.4.0/pom.xml
- papyrus-patch/v4.4.0/site-papyrus-patch/pom.xml
- papyrus-patch/v4.4.0/site-papyrus-patch/site.xml
- papyrus-patch/v4.8.0/com.zeligsoft.papyrus.uml.properties.patch.feature/feature.xml
- papyrus-patch/v4.8.0/com.zeligsoft.papyrus.views.modelexplorer.patch.feature/feature.xml
- papyrus-patch/v4.8.0/pom.xml
- papyrus-patch/v4.8.0/site-papyrus-patch/pom.xml
- papyrus-patch/v4.8.0/site-papyrus-patch/site.xml
- pom.xml
- releng/com.zeligsoft.ddk.update/pom.xml
- releng/com.zeligsoft.dds4ccm.configuration/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/rpm_build/zeligsoftCX_atcd.spec
- releng/com.zeligsoft.dds4ccm.update.axcioma/pom.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.feature/feature.xml
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.product/papyrus-cx-axcioma.product
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.product/pom.xml
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.product/rpm_build/papyrus-cx-axcioma.spec
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/META-INF/MANIFEST.MF
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/about.mappings
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/about.properties
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/plugin.xml
- releng/pom.xml
> Issue #481: Roll version of the main papyrus branch to 2.6.0

- bundles/pom.xml
- ddk/pom.xml
- features/pom.xml
- papyrus-patch/v4.4.0/feature-com.zeligsoft.papyruspatch/category.xml
- papyrus-patch/v4.4.0/feature-com.zeligsoft.papyruspatch/feature.xml
- papyrus-patch/v4.4.0/pom.xml
- papyrus-patch/v4.4.0/site-papyrus-patch/pom.xml
- papyrus-patch/v4.4.0/site-papyrus-patch/site.xml
- papyrus-patch/v4.8.0/com.zeligsoft.papyrus.uml.properties.patch.feature/feature.xml
- papyrus-patch/v4.8.0/com.zeligsoft.papyrus.views.modelexplorer.patch.feature/feature.xml
- papyrus-patch/v4.8.0/pom.xml
- papyrus-patch/v4.8.0/site-papyrus-patch/pom.xml
- papyrus-patch/v4.8.0/site-papyrus-patch/site.xml
- pom.xml
- releng/com.zeligsoft.ddk.update/pom.xml
- releng/com.zeligsoft.dds4ccm.configuration/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/pom.xml
- releng/com.zeligsoft.dds4ccm.update.atcd/rpm_build/zeligsoftCX_atcd.spec
- releng/com.zeligsoft.dds4ccm.update.axcioma/pom.xml
- releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.feature/feature.xml
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.product/papyrus-cx-axcioma.product
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.product/pom.xml
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp.product/rpm_build/papyrus-cx-axcioma.spec
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/META-INF/MANIFEST.MF
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/about.mappings
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/plugin.properties
- releng/com.zeligsoft.papyrus-cx.axcioma.rcp/plugin.xml
- releng/pom.xml
Updated version on the 2.5.x-maintenance branch to 2.5.1
> Issue #481: Roll version of new streams/v2.5.x-maintenance branch to 2.5.1
